mode: 'propogate'               # propogate or merge
multiplier: 70                   # latent_dim=res_dim * d_model
d_models: [768, 768]            # no comments
lambda_l1: 0.5
lambda_cos: 0.5
layer: -2
eval_dataset: './data/shakespeare.txt'     # evaluation dataset
max_len: 32
batch_size: 32
checkpoint_to_test: './results/sae_layer_-2.pt'  # checkpoint to test
